% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\title{Estimation of COVID-19 cases in Ontario\thanks{Code and data are available at: \url{https://github.com/zihanjasmine/Estimation-of-COVID-19-cases-in-Ontario}.}}
\author{Zihan Zhang}
\date{25 四月 2022}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Estimation of COVID-19 cases in Ontario},
  pdfauthor={Zihan Zhang},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslentryspacingunit} % times entry-spacing
\setlength{\cslentryspacingunit}{\parskip}
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{siunitx}
\newcolumntype{d}{S[input-symbols = ()]}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle
\begin{abstract}
COVID-19 is a respiratory disease first discovered in 2019 and then spread across the world. Many people may be facing an increased level of anxiety and stress. In this report, we built a poisson model to estimate the COVID 19 cases in Ontario. We focus on how gender and age group affect the probability of getting COVID-19.
\end{abstract}

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\newpage

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

COVID-19 is an infection disease first discovered in Wuhan, China in 2019 and then spread across the world. The disease spreads through small infected respiratory droplets, the infected droplets may direct contact with mouth, nose, or eyes and result in infection. The use of face masks, vaccinations, and social distancing are effective preventative measures for COVID-19. Evidence shows that people who are unvaccinated have a larger death rate than people who are fully vaccinated. (Nick Andrews 2022) Also, wash your hands often and avoid touching your mouth, nose, and eyes with unwashed hands.

COVID-19 is highly contagious, but the disease has a low fatality rate of less than 6\% in the 20 most affected countries. Most infected people will have symptoms like fever, cough, tiredness, etc. These mild symptoms mainly affect the respiratory system and can be recovered in 10 days without hospitalization. If you experience symptoms like shortness of breath, chest pain, etc., you might need to seek emergency medical attention. However, some patients experience lingering health problems even when they have recovered from the acute phase of the illness. Common post-COVID syndrome includes loss or distortion of the sense of smell and taste, fatigue, chest pain, etc.

In this paper, we will focus on factors that increase the probability of getting severe COVID-19. Based on covid-19 cases data obtained from Open Data Toronto, we built a logistic model to predict the probability of COVID-19 patients getting severe symptoms. We found out that aged, male, sporadic patients are more likely to get severe symptoms that need hospitalization. If we keep age and outbreak associated cases fixed, the odds of requiring hospitalization for males are 1.5 times as large as the odds for females. Since we know from this report that male and aged people have a higher risk of severe illness from covid-19, we need to step up our advocacy and raise awareness of the importance of the COVID-19. We urge people to get vaccinated, wear face masks, and minimize going to crowded places.

The article is structured as follows. We first introduced the background knowledge about COVID-19, then we will perform explanatory data analysis. The method section includes all the statistical methods we used in this paper. Then we compare different models and choose a preferred logistic model to estimate the probability of hospitalization of COVID-19 cases. Finally, we will discuss the limitations of our model and future steps.

\hypertarget{data}{%
\section{Data}\label{data}}

\hypertarget{data-collection}{%
\subsection{Data collection}\label{data-collection}}

To attempt an analysis of severe illness from COVID-19, I manipulated COVID-19 cases data. COVID-19 cases in Toronto dataset were managed by Toronto Public Health. These data are retrieved from Open data Toronto. The dataset was gathered in 2020 and it is refreshed and overwritten every Wednesday. It contains demographic and geographic information about every confirmed COVID-19 cases in Toronto.

\hypertarget{data-processing}{%
\subsection{Data processing}\label{data-processing}}

All analyses were done with a statistic programming language R.(R Core Team 2020) We first use R packages ``opendatatoronto''(Gelfand 2020) and ''tidyverse'' (Wickham et al. 2019)to import our data. Then I cleaned the names of variables and removed missing values for age. The data was done cleaning.

The raw dataset contains 32000 observations in total. I randomly selected 30000 observations to complete an exploratory analysis and modeling. I also set the seed as 1 so that every time we run the code, we can get the same result. The data was divided into two parts- training and test. Usually, the number of training data is more than the number of detection data, so I randomly selected 70\% of data without replacement (21000 observations) as training data. We used the training data for model building and model selection. Then we fitted the optimum logistic model in the test dataset to see whether we can validate the optimum model. Table \ref{tab:trainsummary} and Table \ref{tab:testsummary} show a summary of important variables for both the training and test dataset. We can see that the different levels of each variable account for roughly the same proportion of the two datasets, so we believe that there is no significant difference between the training and test dataset. For example, 50.1\% of the sample is female in the test dataset, and 49.7\% of the sample is female in the training dataset.

\begin{table}

\caption{\label{tab:trainsummary}Summary of categorical variables for training dataset}
\centering
\begin{tabular}[t]{llrr}
\toprule
  &    & N & \%\\
\midrule
outbreak\_associated & Outbreak Associated & 3395 & \num{16.2}\\
 & Sporadic & 17605 & \num{83.8}\\
age\_group & 19 and younger & 3097 & \num{14.7}\\
 & 20 to 29 Years & 4174 & \num{19.9}\\
 & 30 to 39 Years & 3461 & \num{16.5}\\
 & 40 to 49 Years & 3014 & \num{14.4}\\
 & 50 to 59 Years & 3041 & \num{14.5}\\
 & 60 to 69 Years & 1990 & \num{9.5}\\
 & 70 to 79 Years & 948 & \num{4.5}\\
 & 80 to 89 Years & 793 & \num{3.8}\\
 & 90 and older & 482 & \num{2.3}\\
source\_of\_infection & Close Contact & 1172 & \num{5.6}\\
 & Community & 2479 & \num{11.8}\\
 & Household Contact & 3492 & \num{16.6}\\
 & No Information & 10185 & \num{48.5}\\
 & Outbreaks, Congregate Settings & 174 & \num{0.8}\\
 & Outbreaks, Healthcare Institutions & 2057 & \num{9.8}\\
 & Outbreaks, Other Settings & 1330 & \num{6.3}\\
 & Travel & 111 & \num{0.5}\\
classification & CONFIRMED & 20654 & \num{98.4}\\
 & PROBABLE & 346 & \num{1.6}\\
client\_gender & FEMALE & 10436 & \num{49.7}\\
 & MALE & 10564 & \num{50.3}\\
outcome & FATAL & 438 & \num{2.1}\\
 & RESOLVED & 20562 & \num{97.9}\\
 & No & 21000 & \num{100.0}\\
 & No & 21000 & \num{100.0}\\
 & No & 21000 & \num{100.0}\\
ever\_hospitalized & No & 19864 & \num{94.6}\\
 & Yes & 1136 & \num{5.4}\\
ever\_in\_icu & No & 20790 & \num{99.0}\\
 & Yes & 210 & \num{1.0}\\
ever\_intubated & No & 20878 & \num{99.4}\\
 & Yes & 122 & \num{0.6}\\
\bottomrule
\end{tabular}
\end{table}

\begin{table}

\caption{\label{tab:testsummary}Summary of categorical variables for test dataset}
\centering
\begin{tabular}[t]{llrr}
\toprule
  &    & N & \%\\
\midrule
outbreak\_associated & Outbreak Associated & 1479 & \num{16.4}\\
 & Sporadic & 7521 & \num{83.6}\\
age\_group & 19 and younger & 1341 & \num{14.9}\\
 & 20 to 29 Years & 1863 & \num{20.7}\\
 & 30 to 39 Years & 1464 & \num{16.3}\\
 & 40 to 49 Years & 1293 & \num{14.4}\\
 & 50 to 59 Years & 1284 & \num{14.3}\\
 & 60 to 69 Years & 800 & \num{8.9}\\
 & 70 to 79 Years & 422 & \num{4.7}\\
 & 80 to 89 Years & 315 & \num{3.5}\\
 & 90 and older & 218 & \num{2.4}\\
source\_of\_infection & Close Contact & 530 & \num{5.9}\\
 & Community & 1033 & \num{11.5}\\
 & Household Contact & 1465 & \num{16.3}\\
 & No Information & 4385 & \num{48.7}\\
 & Outbreaks, Congregate Settings & 63 & \num{0.7}\\
 & Outbreaks, Healthcare Institutions & 858 & \num{9.5}\\
 & Outbreaks, Other Settings & 623 & \num{6.9}\\
 & Pending & 1 & \num{0.0}\\
 & Travel & 42 & \num{0.5}\\
classification & CONFIRMED & 8846 & \num{98.3}\\
 & PROBABLE & 154 & \num{1.7}\\
client\_gender & FEMALE & 4509 & \num{50.1}\\
 & MALE & 4491 & \num{49.9}\\
outcome & FATAL & 196 & \num{2.2}\\
 & RESOLVED & 8804 & \num{97.8}\\
 & No & 9000 & \num{100.0}\\
 & No & 9000 & \num{100.0}\\
 & No & 9000 & \num{100.0}\\
ever\_hospitalized & No & 8565 & \num{95.2}\\
 & Yes & 435 & \num{4.8}\\
ever\_in\_icu & No & 8909 & \num{99.0}\\
 & Yes & 91 & \num{1.0}\\
ever\_intubated & No & 8955 & \num{99.5}\\
 & Yes & 45 & \num{0.5}\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{data-characteristics}{%
\subsection{Data characteristics}\label{data-characteristics}}

The dataset contains demographic (age group, gender) and geographic (patient's neighborhood name and postal code), and severity (ever hospitalized, ever in ICU, outcome, etc.) information. This information is sensitive and it is possible to identify individuals either directly or indirectly. For example, if you see a case of a transgender patient in your community in the data, combined with age and FSA (first three characters of postal code), it is highly likely that you can identify that person.

First, show an extract of our dataset (figure \ref{datasummary}). We can tell that most variables are categorical variables.

\begin{table}

\caption{\label{tab:datasummary}A glimpse of important varaibles}
\centering
\begin{tabular}[t]{llccccr}
\toprule
Reported date & Age group & Gender & Source of infection & Neighbourhood name & Ever hospitalized & outcome\\
\midrule
2020-10-18 & 20 to 29 Years & MALE & No Information & West Hill & No & RESOLVED\\
2020-10-14 & 30 to 39 Years & FEMALE & No Information & Willowdale East & No & RESOLVED\\
2020-10-15 & 60 to 69 Years & FEMALE & No Information & North Riverdale & No & RESOLVED\\
2020-10-18 & 40 to 49 Years & MALE & No Information & Bendale & No & RESOLVED\\
2020-10-18 & 30 to 39 Years & MALE & Outbreaks, Other Settings & Malvern & No & RESOLVED\\
2020-10-13 & 30 to 39 Years & FEMALE & No Information & Rosedale-Moore Park & No & RESOLVED\\
2020-10-15 & 50 to 59 Years & MALE & Travel & Don Valley Village & No & RESOLVED\\
2020-10-13 & 20 to 29 Years & MALE & No Information & Elms-Old Rexdale & No & RESOLVED\\
2020-10-14 & 20 to 29 Years & FEMALE & No Information & Waterfront Communities-The Island & No & RESOLVED\\
2020-10-17 & 40 to 49 Years & MALE & Outbreaks, Other Settings & Brookhaven-Amesbury & No & RESOLVED\\
\bottomrule
\end{tabular}
\end{table}

\includegraphics{paper_files/figure-latex/gender-1.pdf}
From figure \ref{gender}, The number of people who receive hospitalization is about the same for women and men.

\includegraphics{paper_files/figure-latex/piegraph-1.pdf}

From figure \ref{fig:piegraph}, we can see that young and middle-aged patients only account for a quarter of severe illnesses of COVID-19. Most patients with severe symptoms are over 60 years old.

\includegraphics{paper_files/figure-latex/fatal-1.pdf}

From figure \ref{fig:fatal}, roughly 40\% of all cases that were hospitalized related to their COVID-19 infection are fatal, which indicates there are no effective treatments for patients with severe symptoms of covid.

\includegraphics{paper_files/figure-latex/source-1.pdf}

From figure \ref{fig:source}, the source of infection in half of the cases is unknown and cannot be speculated. Household contact and close contact with covid positive are also important causes of COVID-19 infection. 10\% of COVID patients are infected in healthcare institutions. Healthcare Institutions include hospitals, retirement homes, etc. Usually, people who go to the healthcare institutions for help are mainly the aged population. These people are in poor health conditions and have lower immunity, which makes them more susceptible to viral infections.

\hypertarget{model}{%
\section{Model}\label{model}}

To find out what factors can make you seriously ill after getting covid, I performed logistic regression using R. Through the logistic regression model, I was unable to define causality, but rather explore the relationship between different variables. Since patients with mild symptoms can be recovered in a few days without hospitalization, I consider those who are hospitalized as severe illness of COVID-19. I set ``ever hospitalized'' as the explanatory variable. The variable ``ever hospitalized'' is a binary variable with two levels: Yes and No, which is an appropriate structure of the outcome variable. I recoded the ``ever hospitalized'' and set the outcome variable to be 1 if the patient received hospitalization, and 0 if vice versa. The logistic model is constructed using the R package ``stats.''(R Core Team 2021)

The general form of logistic model is :

\(log(\frac{\hat{p}}{1-\hat{p}}) = X_i\beta\)

\begin{itemize}
\tightlist
\item
  \(\hat{p}\) is the probability of hospitalization given \(X_i\)
\item
  \(X_i\) are covariates for observation i
\item
  \(\beta\) is a vector of regression coefficients
\end{itemize}

I will compare 3 logistic regression models, each with different independent variables, and ultimately choose the optimum model.

\hypertarget{model-construction}{%
\subsection{Model construction}\label{model-construction}}

\hypertarget{model-1}{%
\subsubsection{Model 1}\label{model-1}}

First, I would like to examine the effect of gender and age on the probability of hospitalization.

The first model is :

\(log(\frac{p}{1-p})=\beta_0+\beta_1Client \ gender+\beta_2Age \ group\)
The probability of hospitalization is :
\(\hat{p}=\frac{e^{\hat{\beta_0}+\hat{\beta_1}Client \ gender+\hat{\beta_2}Age \ group}}{e^{\beta_0+\hat{\beta_1}Client \ gender+\hat{\beta_2}Age \ group}+1}\)

\hypertarget{model-2-final-model}{%
\subsubsection{Model 2 (final model)}\label{model-2-final-model}}

On the basis of model 1, I want to study the effect of the variable ``outbreak associated.'' This variable tells us whether the case is associated with a healthcare institution or not.

The second model is :

\(log(\frac{p}{1-p}) = \beta_0 + \beta_1Outbreak \ associated + \beta_2Client \ gender + \beta_3Age \ group\)

The probability of hospitalization is :
\(\hat{p}=\frac{e^{\hat{\beta_0}+ \hat{\beta_1}Outbreak \ associated + \hat{\beta_2}Client \ gender +\hat{\beta_3}Age \ group}}{e^{\hat{\beta_0} + \hat{\beta_1}Outbreak \ associated + \hat{\beta_2}Client \ gender + \hat{\beta_3}Age \ group}+1}\)

\hypertarget{model-3}{%
\subsubsection{Model 3}\label{model-3}}

Based on model 2, I am also interested in whether the interaction term of outbreak associated and gender affect the probability of severe illness of COVID-19.

The third model is :

\(log(\frac{p}{1-p}) = \beta_0 + \beta_1Outbreak \ associated + \beta_2Client \ gender + \beta_3Age \ group +\beta_4Client \ gender:Outbreak \ associated\)

The probability of hospitalization is :

\(\hat{p}=\frac{e^{\hat{\beta_0}+ \hat{\beta_1}Outbreak \ associated + \hat{\beta_2}Client \ gender +\hat{\beta_3}Age \ group+\hat{\beta_4}Client \ gender:Outbreak \ associated}}{e^{\hat{\beta_0} + \hat{\beta_1}Outbreak \ associated + \hat{\beta_2}Client \ gender + \hat{\beta_3}Age \ group+\hat{\beta_4}Client \ gender:Outbreak \ associated}+1}\)

After model construction, I will select the best model in the next step. Then model assumptions will be checked and the preferred model is tested with test data to see if it can be validated.

\hypertarget{result}{%
\section{Result}\label{result}}

After plugging in the data, we obtained the regression coefficients for the three models.

The first model is :

\(log(\frac{\hat{p}}{1-\hat{p}}) = -5.5164+0.434Client \ gender_{Male} + 0.5701Age \ group_{20-29 \ years}+0.8237Age \ group_{30-39 \ years}+1.5476Age \ group_{40-49 \ years} +2.0775Age \ group_{50-59 \ years} +3.0685Age \ group_{60-69 \ years} +4.2582Age \ group_{70-79 \ years}+4.6742Age \ group_{80-89 \ years} +4.4333Age \ group_{90 +}\)

Table \ref{tab:model1} shows a summary of model 1. Most of the predictors are statistically significant at a 0.05 significant level.

\begin{longtable}[]{@{}ccccc@{}}
\caption{\label{tab:model1}A summary of model 1}\tabularnewline
\toprule
term & estimate & std.error & statistic & p.value \\
\midrule
\endfirsthead
\toprule
term & estimate & std.error & statistic & p.value \\
\midrule
\endhead
(Intercept) & -5.5164 & 0.2542 & -21.6975 & 0.0000 \\
client\_genderMALE & 0.4340 & 0.0677 & 6.4076 & 0.0000 \\
age\_group20 to 29 Years & 0.5701 & 0.2989 & 1.9074 & 0.0565 \\
age\_group30 to 39 Years & 0.8237 & 0.2968 & 2.7758 & 0.0055 \\
age\_group40 to 49 Years & 1.5476 & 0.2782 & 5.5623 & 0.0000 \\
age\_group50 to 59 Years & 2.0775 & 0.2676 & 7.7638 & 0.0000 \\
age\_group60 to 69 Years & 3.0685 & 0.2615 & 11.7335 & 0.0000 \\
age\_group70 to 79 Years & 4.2582 & 0.2612 & 16.3004 & 0.0000 \\
age\_group80 to 89 Years & 4.6742 & 0.2620 & 17.8426 & 0.0000 \\
age\_group90 and older & 4.4333 & 0.2712 & 16.3471 & 0.0000 \\
\bottomrule
\end{longtable}

The second model is :

\(log(\frac{\hat{p}}{1-\hat{p}}) =-5.7373 +0.279 Outbreak \ associated_{Sporadic} + 0.4189 Client \ gender_{Male} + 0.537Age \ group_{20-29 \ years}+0.7959Age \ group_{30-39 \ years}+1.5287Age \ group_{40-49 \ years} +2.0612Age \ group_{50-59 \ years} +3.0585Age \ group_{60-69 \ years} + 4.2752Age \ group_{70-79 \ years}+4.7766Age \ group_{80-89 \ years} +4.61334Age \ group_{90 +}\)

Table \ref{tab:model2} shows a summary of model 2.

\begin{longtable}[]{@{}ccccc@{}}
\caption{\label{tab:model2}A summary of model 2}\tabularnewline
\toprule
term & estimate & std.error & statistic & p.value \\
\midrule
\endfirsthead
\toprule
term & estimate & std.error & statistic & p.value \\
\midrule
\endhead
(Intercept) & -5.7373 & 0.2640 & -21.7357 & 0.0000 \\
outbreak\_associatedSporadic & 0.2790 & 0.0874 & 3.1925 & 0.0014 \\
client\_genderMALE & 0.4189 & 0.0679 & 6.1683 & 0.0000 \\
age\_group20 to 29 Years & 0.5370 & 0.2990 & 1.7958 & 0.0725 \\
age\_group30 to 39 Years & 0.7959 & 0.2969 & 2.6810 & 0.0073 \\
age\_group40 to 49 Years & 1.5287 & 0.2783 & 5.4934 & 0.0000 \\
age\_group50 to 59 Years & 2.0612 & 0.2676 & 7.7017 & 0.0000 \\
age\_group60 to 69 Years & 3.0585 & 0.2615 & 11.6945 & 0.0000 \\
age\_group70 to 79 Years & 4.2753 & 0.2613 & 16.3600 & 0.0000 \\
age\_group80 to 89 Years & 4.7766 & 0.2641 & 18.0885 & 0.0000 \\
age\_group90 and older & 4.6133 & 0.2773 & 16.6380 & 0.0000 \\
\bottomrule
\end{longtable}

The third model is :

\(log(\frac{\hat{p}}{1-\hat{p}}) =-5.8792 +0.4807 Outbreak \ associated_{Sporadic} + 0.707 Client \ gender_{Male} + 0.5474Age \ group_{20-29 \ years}+0.8055Age \ group_{30-39 \ years}+1.5366Age \ group_{40-49 \ years} +2.0678Age \ group_{50-59 \ years} +3.0633Age \ group_{60-69 \ years} + 4.2713Age \ group_{70-79 \ years}+4.7898Age \ group_{80-89 \ years} +4.6534Age \ group_{90 +}-0.4029 Outbreak \ associated_{Sporadic}:Client \ gender_{Male}\)

Table \ref{tab:model3} shows a summary of model 3.

\begin{longtable}[]{@{}ccccc@{}}
\caption{\label{tab:model3}A summary of model 3}\tabularnewline
\toprule
term & estimate & std.error & statistic & p.value \\
\midrule
\endfirsthead
\toprule
term & estimate & std.error & statistic & p.value \\
\midrule
\endhead
(Intercept) & -5.8792 & 0.2697 & -21.7974 & 0.0000 \\
outbreak\_associatedSporadic & 0.4807 & 0.1158 & 4.1497 & 0.0000 \\
client\_genderMALE & 0.7070 & 0.1263 & 5.5986 & 0.0000 \\
age\_group20 to 29 Years & 0.5474 & 0.2990 & 1.8304 & 0.0672 \\
age\_group30 to 39 Years & 0.8055 & 0.2969 & 2.7130 & 0.0067 \\
age\_group40 to 49 Years & 1.5366 & 0.2783 & 5.5212 & 0.0000 \\
age\_group50 to 59 Years & 2.0678 & 0.2676 & 7.7259 & 0.0000 \\
age\_group60 to 69 Years & 3.0633 & 0.2615 & 11.7129 & 0.0000 \\
age\_group70 to 79 Years & 4.2713 & 0.2613 & 16.3471 & 0.0000 \\
age\_group80 to 89 Years & 4.7898 & 0.2640 & 18.1418 & 0.0000 \\
age\_group90 and older & 4.6534 & 0.2777 & 16.7567 & 0.0000 \\
outbreak\_associatedSporadic:client\_genderMALE & -0.4029 & 0.1489 & -2.7054 & 0.0068 \\
\bottomrule
\end{longtable}

In order to figure out the optimum model, the likelihood ratio test is performed. The likelihood ratio test helps us access the goodness of fits by maximizing the entire parameter space, which is difficult and time-consuming to calculate by hand. I used the R function ``lrtest( )'' from R package ``lmtest'' (Zeileis and Hothorn 2002) to run the test. The two models to be compared must be nested.

In this case, model 1 is a subset of model 2, so the two models are nested. Table \ref{tab:compare12} shows a likelihood ratio test to compare model 1 and model 2. From table \ref{tab:compare12}, the p-value is 0.0012, which is smaller than 0.05, so we have strong evidence against the null hypothesis that the reduced model (mode 1) better explains the COVID-19 cases data. In conclusion, we believe that model 2 (full model) better explains our data.

\begin{table}

\caption{\label{tab:compare12}Comparison of model 1 and model 2 using the likelihood ratio test}
\centering
\begin{tabular}[t]{r|r|r|r|r}
\hline
\#Df & LogLik & Df & Chisq & Pr(>Chisq)\\
\hline
10 & -3332.750 & NA & NA & NA\\
\hline
11 & -3327.525 & 1 & 10.45149 & 0.0012255\\
\hline
\end{tabular}
\end{table}

Model 2 is a subset of model 3, so I performed a likelihood ratio test to compare mode 2 and model 3. (Table \ref{tab:compare23}) From table \ref{tab:compare23}, the p-value is 0.068, which is greater than 0.05, so we reject the null hypothesis (\(H_0\)) that model 2 better explains the COVID-19 cases data. Compared to model 3, model 2 better explains the data. In conclusion, model 2 is the optimum model.

\begin{table}

\caption{\label{tab:compare23}Comparison of model 2 and model 3 using the likelihood ratio test}
\centering
\begin{tabular}[t]{r|r|r|r|r}
\hline
\#Df & LogLik & Df & Chisq & Pr(>Chisq)\\
\hline
12 & -3323.869 & NA & NA & NA\\
\hline
11 & -3327.525 & -1 & 7.310733 & 0.0068544\\
\hline
\end{tabular}
\end{table}

\hypertarget{model-interpretation}{%
\section{Model interpretation}\label{model-interpretation}}

The optimum model is :

\(log(\frac{\hat{p}}{1-\hat{p}}) =-5.7373 +0.279 Outbreak \ associated_{Sporadic} + 0.4189 Client \ gender_{Male} + 0.537Age \ group_{20-29 \ years}+0.7959Age \ group_{30-39 \ years}+1.5287Age \ group_{40-49 \ years} +2.0612Age \ group_{50-59 \ years} +3.0585Age \ group_{60-69 \ years} + 4.2752Age \ group_{70-79 \ years}+4.7766Age \ group_{80-89 \ years} +4.61334Age \ group_{90 +}\)

\begin{itemize}
\tightlist
\item
  Outbreak associated
  When all other predictors except outbreak associated remain the same, the odds of hospitalization for an outbreak-associated patient is 1.3218 (\(e^{0.279}\)) times large as the odds of hospitalization for a sporadic patient.
\item
  Gender
  When all other predictors except sex remain the same, the odds of hospitalization for a male is 1.5203 times as large as the odds for a female being admitted to a hospital.
\item
  Age group
  When all other predictors except age group remain the same, the odds of hospitalization for a patient aged 20-29 is 1.711 times as large as the odds for a patient aged below 20. The odds of hospitalization for a patient aged 30-39 is 2.2164 (\(e^{0.7959}\)) times as large as the odds for a patient aged below 20. The odds of hospitalization for a patient aged 40-49 is 4.6122 (\(e^{1.5287}\)) times as large as the odds for a patient aged below 20. The odds of hospitalization for a patient aged 50-59 is 7.8554 (\(e^{2.0612}\)) times as large as the odds for a patient aged below 20. The odds of hospitalization for a patient aged 60-69 is 21.2656 (\(e^{3.0585}\)) times as large as the odds for a patient aged below 20. The odds of hospitalization for a patient aged 70-79 is 71.9017 (\(e^{4.2753}\)) times as large as the odds for a patient aged below 20. The odds of hospitalization for a patient aged 80-89 is 118.7(\(e^{4.7766}\)) times as large as the odds for a patient aged below 20. The odds of hospitalization for a patient aged over 90 is 104.9412 (\(e^{4.6534}\)) times as large as the odds for a patient aged below 20.
\end{itemize}

\hypertarget{model-assumption}{%
\section{Model assumption}\label{model-assumption}}

After selecting the model, I will check whether the assumptions of the model are satisfied. It is important to check the assumptions of the model because if the assumptions of the model are not satisfied, it will lead to inaccurate predictions.
The first assumption is the appropriate outcome type. Our response variable is supposed to be a binary variable. For our optimum model, the response variable ``ever hospitalized'' has two levels, Yes and No, which means the first assumption is met. Secondly, I used residual plot to check the independence assumption. From figure \ref{tab:residual}, the residuals are roughly randomly centralized around 0, so the independence assumption holds. Thirdly, we want to ensure the absence of multicollinearity. Multicollinearity refers to a strong linear relationship between predictors, which might result in non-significant predictors, weakened statistical power of our logistic model etc. Multicollinearity is accessed through VIF value, a predictor with a VIF value that exceeds 5 indicates strong multicollinearity, which suggests the predictor might need to be removed. From figure \ref{tab:vif}, since no VIF values exceed 5, we can conclude the absence of multicollinearity assumption is satisfied.

\includegraphics{paper_files/figure-latex/residual-1.pdf}

\begin{table}

\caption{\label{tab:vif}VIF values for different predictors}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
  & GVIF & Df & GVIF\textasciicircum{}(1/(2*Df))\\
\hline
outbreak\_associated & 1.426547 & 1 & 1.194381\\
\hline
client\_gender & 1.039718 & 1 & 1.019665\\
\hline
age\_group & 1.442878 & 8 & 1.023180\\
\hline
\end{tabular}
\end{table}

\hypertarget{model-validation}{%
\subsection{model validation}\label{model-validation}}

\begin{longtable}[]{@{}ccccc@{}}
\caption{\label{tab:m2test}A summary of model 2 using test dataset}\tabularnewline
\toprule
term & estimate & std.error & statistic & p.value \\
\midrule
\endfirsthead
\toprule
term & estimate & std.error & statistic & p.value \\
\midrule
\endhead
(Intercept) & -5.9561 & 0.4033 & -14.7684 & 0.0000 \\
outbreak\_associatedSporadic & 0.4365 & 0.1414 & 3.0866 & 0.0020 \\
client\_genderMALE & 0.5834 & 0.1122 & 5.2012 & 0.0000 \\
age\_group20 to 29 Years & -1.2336 & 0.6913 & -1.7845 & 0.0743 \\
age\_group30 to 39 Years & 0.8155 & 0.4474 & 1.8226 & 0.0684 \\
age\_group40 to 49 Years & 1.5099 & 0.4219 & 3.5785 & 0.0003 \\
age\_group50 to 59 Years & 1.6662 & 0.4162 & 4.0029 & 0.0001 \\
age\_group60 to 69 Years & 2.9996 & 0.3978 & 7.5405 & 0.0000 \\
age\_group70 to 79 Years & 3.9176 & 0.3988 & 9.8241 & 0.0000 \\
age\_group80 to 89 Years & 5.0033 & 0.4028 & 12.4221 & 0.0000 \\
age\_group90 and older & 4.8578 & 0.4184 & 11.6097 & 0.0000 \\
\bottomrule
\end{longtable}

\hypertarget{discussion}{%
\section{Discussion}\label{discussion}}

\hypertarget{purpose-and-summary-for-the-survey}{%
\subsection{Purpose and summary for the survey}\label{purpose-and-summary-for-the-survey}}

\hypertarget{learn-about-the-world}{%
\subsection{Learn about the world}\label{learn-about-the-world}}

\hypertarget{weakness-and-areas-in-the-future}{%
\subsection{Weakness and areas in the future}\label{weakness-and-areas-in-the-future}}

\newpage

\hypertarget{appendix}{%
\section{Appendix}\label{appendix}}

\textbf{Motivation}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \emph{For what purpose was the dataset created? Was there a specific task in mind? Was there a specific gap that needed to be filled? Please provide a description.}

  \begin{itemize}
  \tightlist
  \item
    The dataset was created to enable analysis of the probability of covid-19 patients requiring hospitalization. There was no specific gap that needed to be filled.
  \end{itemize}
\item
  \emph{Who created the dataset (for example, which team, research group) and on behalf of which entity (for example, company, institution, organization)?}

  \begin{itemize}
  \tightlist
  \item
    The dataset is managed by Toronto Public Health.The data are extracted from the provincial Case \& Contact Management System.
  \end{itemize}
\item
  \emph{Who funded the creation of the dataset? If there is an associated grant, please provide the name of the grantor and the grant name and number.}

  \begin{itemize}
  \tightlist
  \item
    The data is funded by City of Toronto government in Toronto, Ontario, Canada.
  \end{itemize}
\item
  \emph{Any other comments?}

  \begin{itemize}
  \tightlist
  \item
    No
  \end{itemize}
\end{enumerate}

\textbf{Composition}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \emph{What do the instances that comprise the dataset represent (for example, documents, photos, people, countries)? Are there multiple types of instances (for example, movies, users, and ratings; people and interactions between them; nodes and edges)? Please provide a description.}

  \begin{itemize}
  \tightlist
  \item
    This data contains all confirmed and probable COVID-19 cases reported to Toronto Public Health. Each observation of the dataset is an individual.
  \end{itemize}
\item
  \emph{How many instances are there in total (of each type, if appropriate)?}

  \begin{itemize}
  \tightlist
  \item
    There are 31997 observations in the clean data.
  \end{itemize}
\item
  \emph{Does the dataset contain all possible instances or is it a sample (not necessarily random) of instances from a larger set? If the dataset is a sample, then what is the larger set? Is the sample representative of the larger set (for example, geographic coverage)? If so, please describe how this representativeness was validated/verified. If it is not representative of the larger set, please describe why not (for example, to cover a more diverse range of instances, because instances were withheld or unavailable).}

  \begin{itemize}
  \tightlist
  \item
    The dataset contains all confirmed and probable COVID-19 cases in Toronto. It can be considered as s subset of COVID-19 cases in Ontario.
  \end{itemize}
\item
  \emph{What data does each instance consist of? ``Raw'' data (for example, unprocessed text or images) or features? In either case, please provide a description.}

  \begin{itemize}
  \tightlist
  \item
    Each instance consist of demographic (age group, gender) and geographic (patient's neighbourhood name and postal code), and severity (ever hospitalized, ever in icu, outcome etc.) information.
  \end{itemize}
\item
  \emph{Is there a label or target associated with each instance? If so, please provide a description.}

  \begin{itemize}
  \tightlist
  \item
    Yes, every observation has a unique assigned ID.
  \end{itemize}
\item
  \emph{Is any information missing from individual instances? If so, please provide a description, explaining why this information is missing (for example, because it was unavailable). This does not include intentionally removed information, but might include, for example, redacted text.}

  \begin{itemize}
  \tightlist
  \item
    Age group, neighborhood name and fsa is not available in all cases. If the patient is not a Canadian citizen, but a visitor, information such as neighborhood name and fsa may be missing.
  \end{itemize}
\item
  \emph{Are relationships between individual instances made explicit (for example, users' movie ratings, social network links)? If so, please describe how these relationships are made explicit.}

  \begin{itemize}
  \tightlist
  \item
    Yes, through the unique assigned ID.
  \end{itemize}
\item
  \emph{Are there recommended data splits (for example, training, development/validation, testing)? If so, please provide a description of these splits, explaining the rationale behind them.}

  \begin{itemize}
  \tightlist
  \item
    No.~In this paper, 70\% of the dataset goes into the training set and 20\% of the dataset goes into the testing set.
  \end{itemize}
\item
  \emph{Are there any errors, sources of noise, or redundancies in the dataset? If so, please provide a description.}

  \begin{itemize}
  \tightlist
  \item
    NO.
  \end{itemize}
\item
  \emph{Is the dataset self-contained, or does it link to or otherwise rely on external resources (for example, websites, tweets, other datasets)? If it links to or relies on external resources, a) are there guarantees that they will exist, and remain constant, over time; b) are there official archival versions of the complete dataset (that is, including the external resources as they existed at the time the dataset was created); c) are there any restrictions (for example, licenses, fees) associated with any of the external resources that might apply to a dataset consumer? Please provide descriptions of all external resources and any restrictions associated with them, as well as links or other access points, as appropriate.}

  \begin{itemize}
  \tightlist
  \item
    The dataset rely on open data Toronto website. The data are subject to change as public health investigations into reported cases are ongoing. The consumer should follow Open Data License. The dataset is available from \url{https://open.toronto.ca/dataset/covid-19-cases-in-toronto/}.\\
  \end{itemize}
\item
  \emph{Does the dataset contain data that might be considered confidential (for example, data that is protected by legal privilege or by doctor-patient confidentiality, data that includes the content of individuals' non-public communications)? If so, please provide a description.}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\item
  \emph{Does the dataset contain data that, if viewed directly, might be offensive, insulting, threatening, or might otherwise cause anxiety? If so, please describe why.}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\item
  \emph{Does the dataset identify any sub-populations (for example, by age, gender)? If so, please describe how these subpopulations are identified and provide a description of their respective distributions within the dataset.}

  \begin{itemize}
  \tightlist
  \item
    Yes. The dataset identifies sub-populations by age, gender, and neighborhood name.
  \end{itemize}
\item
  \emph{Is it possible to identify individuals (that is, one or more natural persons), either directly or indirectly (that is, in combination with other data) from the dataset? If so, please describe how.}

  \begin{itemize}
  \tightlist
  \item
    Yes. It is likely to identify someone combined with age group, gender, neighborhood name, and other datasets.
  \end{itemize}
\item
  \emph{Does the dataset contain data that might be considered sensitive in any way (for example, data that reveals race or ethnic origins, sexual orientations, religious beliefs, political opinions or union memberships, or locations; financial or health data; biometric or genetic data; forms of government identification, such as social security numbers; criminal history)? If so, please provide a description.}

  \begin{itemize}
  \tightlist
  \item
    The dataset contains sensitive information, such as neighborhood name, and whether they are incubated or admitted to ICU.
  \end{itemize}
\item
  \emph{Any other comments?}

  \begin{itemize}
  \tightlist
  \item
    No
  \end{itemize}
\end{enumerate}

\textbf{Collection process}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \emph{How was the data associated with each instance acquired? Was the data directly observable (for example, raw text, movie ratings), reported by subjects (for example, survey responses), or indirectly inferred/derived from other data (for example, part-of-speech tags, model-based guesses for age or language)? If the data was reported by subjects or indirectly inferred/derived from other data, was the data validated/verified? If so, please describe how.}

  \begin{itemize}
  \tightlist
  \item
    The data ware gathered from the provincial Case \& Contact Management System.
  \end{itemize}
\item
  \emph{What mechanisms or procedures were used to collect the data (for example, hardware apparatuses or sensors, manual human curation, software programs, software APIs)? How were these mechanisms or procedures validated?}

  \begin{itemize}
  \tightlist
  \item
    The dataset was downloaded from Open Data Toronto.
  \end{itemize}
\item
  \emph{If the dataset is a sample from a larger set, what was the sampling strategy (for example, deterministic, probabilistic with specific sampling probabilities)?}

  \begin{itemize}
  \tightlist
  \item
    The dataset is not a sample.
  \end{itemize}
\item
  \emph{Who was involved in the data collection process (for example, students, crowdworkers, contractors) and how were they compensated (for example, how much were crowdworkers paid)?}

  \begin{itemize}
  \tightlist
  \item
    The dataset was collected by Toronto Public Health.
  \end{itemize}
\item
  \emph{Over what timeframe was the data collected? Does this timeframe match the creation timeframe of the data associated with the instances (for example, recent crawl of old news articles)? If not, please describe the timeframe in which the data associated with the instances was created.}

  \begin{itemize}
  \tightlist
  \item
    The data was collected from January 2020 to now. It is updated on a weekly basis.
  \end{itemize}
\item
  \emph{Were any ethical review processes conducted (for example, by an institutional review board)? If so, please provide a description of these review processes, including the outcomes, as well as a link or other access point to any supporting documentation.}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\item
  \emph{Did you collect the data from the individuals in question directly, or obtain it via third parties or other sources (for example, websites)?}

  \begin{itemize}
  \tightlist
  \item
    The data was collected by Toronto Public Health.
  \end{itemize}
\item
  \emph{Were the individuals in question notified about the data collection? If so, please describe (or show with screenshots or other information) how notice was provided, and provide a link or other access point to, or otherwise reproduce, the exact language of the notification itself.}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\item
  \emph{Did the individuals in question consent to the collection and use of their data? If so, please describe (or show with screenshots or other information) how consent was requested and provided, and provide a link or other access point to, or otherwise reproduce, the exact language to which the individuals consented.}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\item
  \emph{If consent was obtained, were the consenting individuals provided with a mechanism to revoke their consent in the future or for certain uses? If so, please provide a description, as well as a link or other access point to the mechanism (if appropriate).}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\item
  \emph{Has an analysis of the potential impact of the dataset and its use on data subjects (for example, a data protection impact analysis) been conducted? If so, please provide a description of this analysis, including the outcomes, as well as a link or other access point to any supporting documentation.}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\item
  \emph{Any other comments?}

  \begin{itemize}
  \tightlist
  \item
    No
  \end{itemize}
\end{enumerate}

\textbf{Preprocessing/cleaning/labeling}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \emph{Was any preprocessing/cleaning/labeling of the data done (for example, discretization or bucketing, tokenization, part-of-speech tagging, SIFT feature extraction, removal of instances, processing of missing values)? If so, please provide a description. If not, you may skip the remaining questions in this section.}

  \begin{itemize}
  \tightlist
  \item
    Yes, cleaning of the data was done. Missing values of age is removed.
  \end{itemize}
\item
  \emph{Was the ``raw'' data saved in addition to the preprocessed/cleaned/labeled data (for example, to support unanticipated future uses)? If so, please provide a link or other access point to the ``raw'' data.}

  \begin{itemize}
  \tightlist
  \item
    Yes. It is available through Github.
  \end{itemize}
\item
  \emph{Is the software that was used to preprocess/clean/label the data available? If so, please provide a link or other access point.}

  \begin{itemize}
  \tightlist
  \item
    R was used.
  \end{itemize}
\item
  \emph{Any other comments?}

  \begin{itemize}
  \tightlist
  \item
    No
  \end{itemize}
\end{enumerate}

\textbf{Uses}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \emph{Has the dataset been used for any tasks already? If so, please provide a description.}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\item
  \emph{Is there a repository that links to any or all papers or systems that use the dataset? If so, please provide a link or other access point.}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\item
  \emph{What (other) tasks could the dataset be used for?}

  \begin{itemize}
  \tightlist
  \item
    The data can be used to analyze the Toronto epidemic.
  \end{itemize}
\item
  \emph{Is there anything about the composition of the dataset or the way it was collected and preprocessed/cleaned/labeled that might impact future uses? For example, is there anything that a dataset consumer might need to know to avoid uses that could result in unfair treatment of individuals or groups (for example, stereotyping, quality of service issues) or other risks or harms (for example, legal risks, financial harms)? If so, please provide a description. Is there anything a dataset consumer could do to mitigate these risks or harms?}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\item
  \emph{Are there tasks for which the dataset should not be used? If so, please provide a description.}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\item
  \emph{Any other comments?}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\end{enumerate}

\textbf{Distribution}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \emph{Will the dataset be distributed to third parties outside of the entity (for example, company, institution, organization) on behalf of which the dataset was created? If so, please provide a description.}

  \begin{itemize}
  \tightlist
  \item
    The dataset is available from \url{https://open.toronto.ca/dataset/covid-19-cases-in-toronto/}.\\
  \end{itemize}
\item
  \emph{How will the dataset be distributed (for example, tarball on website, API, GitHub)? Does the dataset have a digital object identifier (DOI)?}

  \begin{itemize}
  \tightlist
  \item
    The dataset is distributed through API.
  \end{itemize}
\item
  \emph{When will the dataset be distributed?}

  \begin{itemize}
  \tightlist
  \item
    The dataset was first published in January 2020.
  \end{itemize}
\item
  \emph{Will the dataset be distributed under a copyright or other intellectual property (IP) license, and/or under applicable terms of use (ToU)? If so, please describe this license and/ or ToU, and provide a link or other access point to, or otherwise reproduce, any relevant licensing terms or ToU, as well as any fees associated with these restrictions.}

  \begin{itemize}
  \tightlist
  \item
    The dataset is under Open Data License.
  \end{itemize}
\item
  \emph{Have any third parties imposed IP-based or other restrictions on the data associated with the instances? If so, please describe these restrictions, and provide a link or other access point to, or otherwise reproduce, any relevant licensing terms, as well as any fees associated with these restrictions.}

  \begin{itemize}
  \tightlist
  \item
    None that are known.
  \end{itemize}
\item
  \emph{Do any export controls or other regulatory restrictions apply to the dataset or to individual instances? If so, please describe these restrictions, and provide a link or other access point to, or otherwise reproduce, any supporting documentation.}

  \begin{itemize}
  \tightlist
  \item
    None that are known.
  \end{itemize}
\item
  \emph{Any other comments?}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\end{enumerate}

\textbf{Maintenance}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \emph{Who will be supporting/hosting/maintaining the dataset?}

  \begin{itemize}
  \tightlist
  \item
    The dataset is supported by Toronto Public Health.
  \end{itemize}
\item
  \emph{How can the owner/curator/manager of the dataset be contacted (for example, email address)?}

  \begin{itemize}
  \tightlist
  \item
    The publisher's email is \href{mailto:edau@toronto.ca}{\nolinkurl{edau@toronto.ca}}.
  \end{itemize}
\item
  \emph{Is there an erratum? If so, please provide a link or other access point.}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\item
  \emph{Will the dataset be updated (for example, to correct labeling errors, add new instances, delete instances)? If so, please describe how often, by whom, and how updates will be communicated to dataset consumers (for example, mailing list, GitHub)?}

  \begin{itemize}
  \tightlist
  \item
    The dataset will be refreshed and overwritten every Wednesday. The dataset is available from \url{https://open.toronto.ca/dataset/covid-19-cases-in-toronto/}.
  \end{itemize}
\item
  \emph{If the dataset relates to people, are there applicable limits on the retention of the data associated with the instances (for example, were the individuals in question told that their data would be retained for a fixed period of time and then deleted)? If so, please describe these limits and explain how they will be enforced.}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\item
  \emph{Will older versions of the dataset continue to be supported/hosted/maintained? If so, please describe how. If not, please describe how its obsolescence will be communicated to dataset consumers.}

  \begin{itemize}
  \tightlist
  \item
    No.The data is just updated.
  \end{itemize}
\item
  \emph{If others want to extend/augment/build on/contribute to the dataset, is there a mechanism for them to do so? If so, please provide a description. Will these contributions be validated/verified? If so, please describe how. If not, why not? Is there a process for communicating/distributing these contributions to dataset consumers? If so, please provide a description.}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\item
  \emph{Any other comments?}

  \begin{itemize}
  \tightlist
  \item
    No.
  \end{itemize}
\end{enumerate}

\newpage

\hypertarget{reference}{%
\section{Reference}\label{reference}}

Mortality analyses. Johns Hopkins Coronavirus Resource Center. (n.d.). Retrieved March 31, 2022, from \url{https://coronavirus.jhu.edu/data/mortality}

World Health Organization. (n.d.). Coronavirus. World Health Organization. Retrieved March 31, 2022, from \url{https://www.who.int/health-topics/coronavirus\#tab=tab_1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{citation}\NormalTok{(}\AttributeTok{package=}\StringTok{"lmtest"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## To cite lmtest in publications use:
## 
##   Achim Zeileis, Torsten Hothorn (2002). Diagnostic Checking in
##   Regression Relationships. R News 2(3), 7-10. URL
##   https://CRAN.R-project.org/doc/Rnews/
## 
## LaTeX的用户的BibTeX条目是
## 
##   @Article{,
##     title = {Diagnostic Checking in Regression Relationships},
##     author = {Achim Zeileis and Torsten Hothorn},
##     journal = {R News},
##     year = {2002},
##     volume = {2},
##     number = {3},
##     pages = {7--10},
##     url = {https://CRAN.R-project.org/doc/Rnews/},
##   }
\end{verbatim}

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-opendatatoronto}{}}%
Gelfand, Sharla. 2020. \emph{Opendatatoronto: Access the City of Toronto Open Data Portal}. \url{https://CRAN.R-project.org/package=opendatatoronto}.

\leavevmode\vadjust pre{\hypertarget{ref-vaccine}{}}%
Nick Andrews, Elise Tessier. 2022. {``Duration of Protection Against Mild and Severe Disease by Covid-19 Vaccines.''}

\leavevmode\vadjust pre{\hypertarget{ref-citeR}{}}%
R Core Team. 2020. \emph{R: A Language and Environment for Statistical Computing}. Vienna, Austria: R Foundation for Statistical Computing. \url{https://www.R-project.org/}.

\leavevmode\vadjust pre{\hypertarget{ref-stats}{}}%
---------. 2021. \emph{R: A Language and Environment for Statistical Computing}. Vienna, Austria: R Foundation for Statistical Computing. \url{https://www.R-project.org/}.

\leavevmode\vadjust pre{\hypertarget{ref-tidyverse}{}}%
Wickham, Hadley, Mara Averick, Jennifer Bryan, Winston Chang, Lucy D'Agostino McGowan, Romain Fran??ois, Garrett Grolemund, et al. 2019. {``Welcome to the {tidyverse}.''} \emph{Journal of Open Source Software} 4 (43): 1686. \url{https://doi.org/10.21105/joss.01686}.

\leavevmode\vadjust pre{\hypertarget{ref-lmtest}{}}%
Zeileis, Achim, and Torsten Hothorn. 2002. {``Diagnostic Checking in Regression Relationships.''} \emph{R News} 2 (3): 7--10. \url{https://CRAN.R-project.org/doc/Rnews/}.

\end{CSLReferences}

\end{document}
